# Generated by Django 5.2.5 on 2026-09-07 23:43

import django.db.models.deletion
import videos.youtube
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('articles', '0007_categoriearticle_article_en_vedette_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=160, verbose_name='Titre')),
                ('titre_fr', models.CharField(max_length=160, null=True, verbose_name='Titre')),
                ('titre_de', models.CharField(max_length=160, null=True, verbose_name='Titre')),
                ('titre_en', models.CharField(max_length=160, null=True, verbose_name='Titre')),
                ('slug', models.SlugField(blank=True, max_length=180, unique=True)),
                ('description', models.TextField(verbose_name='Description')),
                ('description_fr', models.TextField(null=True, verbose_name='Description')),
                ('description_de', models.TextField(null=True, verbose_name='Description')),
                ('description_en', models.TextField(null=True, verbose_name='Description')),
                ('youtube_url', models.URLField(validators=[videos.youtube.validate_youtube_url], verbose_name='URL YouTube')),
                ('miniature', models.ImageField(blank=True, upload_to='videos/thumbnails/', verbose_name='Miniature')),
                ('miniature_alt', models.CharField(blank=True, default='', max_length=255, verbose_name='Texte alternatif de la miniature')),
                ('miniature_alt_fr', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Texte alternatif de la miniature')),
                ('miniature_alt_de', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Texte alternatif de la miniature')),
                ('miniature_alt_en', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Texte alternatif de la miniature')),
                ('date_publication', models.DateTimeField(auto_now_add=True, verbose_name='Date de publication')),
                ('est_publie', models.BooleanField(default=False, verbose_name='Publiée')),
                ('is_premium', models.BooleanField(default=False, verbose_name='Contenu premium')),
                ('en_vedette', models.BooleanField(default=False, verbose_name='À la une')),
                ('ordre_affichage', models.PositiveIntegerField(blank=True, null=True, verbose_name='Ordre d’affichage')),
                ('auteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videos', to=settings.AUTH_USER_MODEL, verbose_name='Auteur')),
                ('categorie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videos', to='articles.categoriearticle', verbose_name='Catégorie')),
            ],
            options={
                'verbose_name': 'Vidéo',
                'verbose_name_plural': 'Vidéos',
            },
        ),
    ]
