# Generated by Django 4.2.7 on 2025-08-18 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("shop", "0004_commande_currency_commande_payment_channel_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("montant", models.DecimalField(decimal_places=2, max_digits=10)),
                ("devise", models.CharField(default="EUR", max_length=10)),
                ("transaction_id", models.CharField(max_length=100, unique=True)),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("STRIPE", "Stripe"),
                            ("MOBILE_MONEY", "Mobile Money"),
                            ("CINETPAY", "CinetPay"),
                            ("CARD", "Carte bancaire"),
                            ("OTHER", "Autre"),
                        ],
                        default="STRIPE",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "En attente"),
                            ("SUCCESS", "Réussi"),
                            ("FAILED", "Échoué"),
                            ("CANCELED", "Annulé"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("raw_response", models.JSONField(blank=True, null=True)),
                (
                    "commande",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="shop.commande",
                    ),
                ),
            ],
        ),
    ]
