# Generated by Django 4.2.7 on 2025-08-19 17:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("payments", "0002_adresse"),
    ]

    operations = [
        migrations.AddField(
            model_name="adresse",
            name="type_adresse",
            field=models.CharField(
                choices=[
                    ("LIVRAISON", "Adresse de livraison"),
                    ("FACTURATION", "Adresse de facturation"),
                ],
                default="LIVRAISON",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="adresse",
            name="utilisateur",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="adresses",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
