# Generated by Django 5.2.5 on 2026-09-09

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("monetization", "0005_abonnement_stripe_price_id_and_more"),
        ("payments", "0006_donationpaymentattempt"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StripeWebhookEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "stripe_event_id",
                    models.CharField(max_length=255, unique=True),
                ),
                ("event_type", models.CharField(max_length=100)),
                ("processed_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="StripeSubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("montant", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "devise",
                    models.CharField(
                        choices=[("EUR", "EUR")],
                        default="EUR",
                        max_length=3,
                    ),
                ),
                ("stripe_price_id", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PROCESSING", "En cours"),
                            ("CHECKOUT_COMPLETE", "Checkout terminé"),
                            ("ACTIVE", "Actif"),
                            ("PAST_DUE", "Paiement en retard"),
                            ("CANCELED", "Annulé"),
                            ("FAILED", "Échoué"),
                        ],
                        default="PROCESSING",
                        max_length=20,
                    ),
                ),
                (
                    "stripe_checkout_session_id",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "stripe_customer_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "stripe_subscription_id",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "idempotency_key",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                    ),
                ),
                ("checkout_url", models.URLField(blank=True, max_length=500)),
                (
                    "current_period_start",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "current_period_end",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("cancel_at_period_end", models.BooleanField(default=False)),
                ("raw_response", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "abonnement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stripe_subscriptions",
                        to="monetization.abonnement",
                    ),
                ),
                (
                    "abonnement_utilisateur",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stripe_subscription",
                        to="monetization.abonnementutilisateur",
                    ),
                ),
                (
                    "utilisateur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stripe_subscriptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StripeSubscriptionInvoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "stripe_invoice_id",
                    models.CharField(max_length=255, unique=True),
                ),
                (
                    "montant_paye",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "devise",
                    models.CharField(
                        choices=[("EUR", "EUR")],
                        default="EUR",
                        max_length=3,
                    ),
                ),
                ("period_start", models.DateTimeField()),
                ("period_end", models.DateTimeField()),
                ("raw_response", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "revenu",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stripe_subscription_invoice",
                        to="monetization.revenu",
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="invoices",
                        to="payments.stripesubscription",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="stripesubscription",
            constraint=models.CheckConstraint(
                condition=models.Q(("montant__gt", 0)),
                name="stripe_subscription_positive_amount",
            ),
        ),
        migrations.AddConstraint(
            model_name="stripesubscription",
            constraint=models.CheckConstraint(
                condition=models.Q(("devise", "EUR")),
                name="stripe_subscription_eur_only",
            ),
        ),
        migrations.AddConstraint(
            model_name="stripesubscription",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    (
                        "status__in",
                        (
                            "PROCESSING",
                            "CHECKOUT_COMPLETE",
                            "ACTIVE",
                            "PAST_DUE",
                        ),
                    )
                ),
                fields=("utilisateur",),
                name="one_open_stripe_subscription_per_user",
            ),
        ),
        migrations.AddConstraint(
            model_name="stripesubscriptioninvoice",
            constraint=models.CheckConstraint(
                condition=models.Q(("montant_paye__gt", 0)),
                name="stripe_subscription_invoice_positive_amount",
            ),
        ),
        migrations.AddConstraint(
            model_name="stripesubscriptioninvoice",
            constraint=models.CheckConstraint(
                condition=models.Q(("devise", "EUR")),
                name="stripe_subscription_invoice_eur_only",
            ),
        ),
        migrations.AddConstraint(
            model_name="stripesubscriptioninvoice",
            constraint=models.CheckConstraint(
                condition=models.Q(("period_end__gt", models.F("period_start"))),
                name="stripe_subscription_invoice_valid_period",
            ),
        ),
    ]
