# Generated by Django 5.0.14 on 2025-08-04 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_article_auteur_alter_article_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='est_sponsorise',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='article',
            name='is_premium',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='article',
            name='sponsor',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
