# Generated by Django 5.2.5 on 2025-09-13 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0003_article_est_sponsorise_article_is_premium_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ArticleMedia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("image", "Image"), ("video", "Vidéo")], max_length=10
                    ),
                ),
                ("fichier", models.FileField(upload_to="medias/")),
                ("date_ajout", models.DateTimeField(auto_now_add=True)),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medias",
                        to="articles.article",
                    ),
                ),
            ],
        ),
    ]
