# Generated by Django 5.2.5 on 2026-09-05 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_articlemedia'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='contenu_de',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='contenu_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='contenu_fr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='titre_de',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='titre_en',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='titre_fr',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
