# Generated by Django 5.2.5 on 2026-09-07 21:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_populate_french_article_translations'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorieArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('nom_fr', models.CharField(max_length=100, null=True)),
                ('nom_de', models.CharField(max_length=100, null=True)),
                ('nom_en', models.CharField(max_length=100, null=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Catégorie d’article',
                'verbose_name_plural': 'Catégories d’articles',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='en_vedette',
            field=models.BooleanField(default=False, verbose_name='À la une'),
        ),
        migrations.AddField(
            model_name='article',
            name='image_alt',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Texte alternatif de l’image'),
        ),
        migrations.AddField(
            model_name='article',
            name='image_alt_de',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Texte alternatif de l’image'),
        ),
        migrations.AddField(
            model_name='article',
            name='image_alt_en',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Texte alternatif de l’image'),
        ),
        migrations.AddField(
            model_name='article',
            name='image_alt_fr',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Texte alternatif de l’image'),
        ),
        migrations.AddField(
            model_name='article',
            name='ordre_affichage',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Ordre d’affichage'),
        ),
        migrations.AddField(
            model_name='article',
            name='categorie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='articles.categoriearticle', verbose_name='Catégorie'),
        ),
    ]
