# Generated by Django 4.2.7 on 2025-08-21 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monetization", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DemandeAffiliation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=150)),
                ("email", models.EmailField(max_length=254)),
                ("plateforme", models.CharField(max_length=100)),
                ("produit", models.CharField(max_length=200)),
                ("message", models.TextField()),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("traite", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="DemandePartenariat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=150)),
                ("email", models.EmailField(max_length=254)),
                ("entreprise", models.CharField(blank=True, max_length=200, null=True)),
                ("message", models.TextField()),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("traite", models.BooleanField(default=False)),
            ],
        ),
    ]
