# Generated by Django 5.2.5 on 2026-09-07 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monetization', '0002_demandeaffiliation_demandepartenariat'),
    ]

    operations = [
        migrations.AddField(
            model_name='abonnement',
            name='description_de',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='abonnement',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='abonnement',
            name='description_fr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='abonnement',
            name='nom_de',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='abonnement',
            name='nom_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='abonnement',
            name='nom_fr',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='publicite',
            name='titre_de',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='publicite',
            name='titre_en',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='publicite',
            name='titre_fr',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
