# Generated by Django 5.2.5 on 2026-09-09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("monetization", "0004_populate_french_monetization_translations"),
    ]

    operations = [
        migrations.AddField(
            model_name="abonnement",
            name="stripe_price_id",
            field=models.CharField(
                blank=True,
                help_text="Identifiant Stripe Price, laissé vide hors facturation.",
                max_length=255,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message=(
                            "L’identifiant Stripe doit commencer par price_."
                        ),
                        regex="^price_[A-Za-z0-9_]+$",
                    )
                ],
            ),
        ),
        migrations.AddConstraint(
            model_name="abonnement",
            constraint=models.UniqueConstraint(
                condition=(
                    models.Q(("stripe_price_id__isnull", False))
                    & ~models.Q(("stripe_price_id", ""))
                ),
                fields=("stripe_price_id",),
                name="unique_configured_subscription_stripe_price",
            ),
        ),
    ]
