# Generated by Django 5.2.5 on 2026-09-22 19:00

from datetime import time

import django.core.validators
from django.db import migrations, models


def preserve_inclusive_legacy_end_dates(apps, schema_editor):
    """Keep the final day of legacy DateField campaigns publicly available."""
    Campaign = apps.get_model("monetization", "Publicite")
    database = schema_editor.connection.alias
    for campaign in Campaign.objects.using(database).exclude(date_fin=None).iterator():
        if campaign.date_fin.time() == time.min:
            Campaign.objects.using(database).filter(pk=campaign.pk).update(
                date_fin=campaign.date_fin.replace(
                    hour=23,
                    minute=59,
                    second=59,
                    microsecond=999999,
                )
            )


class Migration(migrations.Migration):

    dependencies = [
        ('monetization', '0005_abonnement_stripe_price_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publicite',
            options={'ordering': ('ordre', 'pk')},
        ),
        migrations.AddField(
            model_name='publicite',
            name='description',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='publicite',
            name='description_de',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='publicite',
            name='description_en',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='publicite',
            name='description_fr',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='publicite',
            name='ordre',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='publicite',
            name='texte_alternatif',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='publicite',
            name='texte_alternatif_de',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='publicite',
            name='texte_alternatif_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='publicite',
            name='texte_alternatif_fr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='publicite',
            name='texte_cta',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='publicite',
            name='texte_cta_de',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='publicite',
            name='texte_cta_en',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='publicite',
            name='texte_cta_fr',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='publicite',
            name='date_debut',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='publicite',
            name='date_fin',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='publicite',
            name='lien',
            field=models.URLField(max_length=500, validators=[django.core.validators.URLValidator(schemes=('http', 'https'))]),
        ),
        migrations.RunPython(
            preserve_inclusive_legacy_end_dates,
            migrations.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name='publicite',
            constraint=models.CheckConstraint(condition=models.Q(('date_debut__isnull', True), ('date_fin__isnull', True), ('date_debut__lte', models.F('date_fin')), _connector='OR'), name='publicite_period_is_chronological'),
        ),
    ]
