# Generated by Django 5.0.14 on 2025-08-04 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('prix', models.DecimalField(decimal_places=2, max_digits=8)),
                ('image', models.ImageField(upload_to='produits/')),
                ('fichier', models.FileField(blank=True, null=True, upload_to='produits/fichiers/')),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
    ]
