# Generated by Django 4.2.7 on 2025-08-18 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0003_produit_categorie_produit_en_vedette"),
    ]

    operations = [
        migrations.AddField(
            model_name="commande",
            name="currency",
            field=models.CharField(default="EUR", max_length=10),
        ),
        migrations.AddField(
            model_name="commande",
            name="payment_channel",
            field=models.CharField(
                blank=True,
                choices=[
                    ("CARD", "Carte bancaire"),
                    ("MOBILE_MONEY", "Mobile Money"),
                    ("STRIPE", "Stripe"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="commande",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("PENDING", "En attente"),
                    ("SUCCESS", "Payée"),
                    ("FAILED", "Échouée"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="commande",
            name="transaction_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="categorie",
            name="slug",
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name="commande",
            name="total",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="lignecommande",
            name="prix_unitaire",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="produit",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="produit",
            name="prix",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="produit",
            name="slug",
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
