# Generated by Django 4.2.7 on 2025-08-19 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0002_adresse"),
        ("shop", "0004_commande_currency_commande_payment_channel_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="commande",
            name="adresse",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="commandes",
                to="payments.adresse",
            ),
        ),
        migrations.AlterField(
            model_name="commande",
            name="currency",
            field=models.CharField(
                choices=[("EUR", "Euro"), ("USD", "Dollar"), ("XOF", "Franc CFA")],
                default="EUR",
                max_length=10,
            ),
        ),
    ]
