# Generated by Django 5.2.5 on 2026-09-04 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_cart_integrity_constraints'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorie',
            name='nom_de',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='categorie',
            name='nom_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='categorie',
            name='nom_fr',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='produit',
            name='description_de',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='produit',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='produit',
            name='description_fr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='produit',
            name='nom_de',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='produit',
            name='nom_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='produit',
            name='nom_fr',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
