# Generated by Django 5.2.5 on 2026-09-07 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_populate_french_product_category_translations'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='language_code',
            field=models.CharField(choices=[('fr', 'Français'), ('de', 'Allemand'), ('en', 'Anglais')], default='fr', max_length=10),
        ),
    ]
