# Generated by Django 5.2.5 on 2026-09-11 12:30

from pathlib import PurePosixPath

import django.db.models.deletion
from django.core.exceptions import SuspiciousFileOperation
from django.db import migrations, models
from django.utils.text import get_valid_filename


SNAPSHOT_FIELDS = (
    "nom_produit_snapshot",
    "fichier_nom_stockage_snapshot",
    "fichier_nom_telechargement_snapshot",
)


def safe_download_filename(storage_name):
    normalized_name = str(storage_name or "").replace("\\", "/")
    if not normalized_name:
        return ""

    basename = PurePosixPath(normalized_name).name
    if not basename:
        return "fichier-commande"
    try:
        return get_valid_filename(basename)
    except SuspiciousFileOperation:
        return "fichier-commande"


def order_product_snapshot_name(product, language_code):
    language_fields = {
        "fr": "nom_fr",
        "de": "nom_de",
        "en": "nom_en",
    }
    requested_language = (
        language_code if language_code in language_fields else "fr"
    )
    fallback_languages = (requested_language, "fr", "de", "en")
    for candidate_language in dict.fromkeys(fallback_languages):
        value = getattr(product, language_fields[candidate_language], "") or ""
        if value.strip():
            return value
    return "Produit indisponible"


def backfill_order_line_snapshots(apps, schema_editor):
    database = schema_editor.connection.alias
    LigneCommande = apps.get_model("shop", "LigneCommande")
    lines = LigneCommande.objects.using(database).filter(produit__isnull=False)

    batch = []
    historical_lines = lines.select_related("commande", "produit").iterator(
        chunk_size=500
    )
    for line in historical_lines:
        product = line.produit
        storage_name = product.fichier.name if product.fichier else ""
        line.nom_produit_snapshot = order_product_snapshot_name(
            product,
            line.commande.language_code,
        )
        line.fichier_nom_stockage_snapshot = storage_name
        line.fichier_nom_telechargement_snapshot = safe_download_filename(
            storage_name
        )
        batch.append(line)
        if len(batch) == 500:
            LigneCommande.objects.using(database).bulk_update(
                batch,
                SNAPSHOT_FIELDS,
            )
            batch = []

    if batch:
        LigneCommande.objects.using(database).bulk_update(batch, SNAPSHOT_FIELDS)


def clear_order_line_snapshots(apps, schema_editor):
    database = schema_editor.connection.alias
    LigneCommande = apps.get_model("shop", "LigneCommande")
    LigneCommande.objects.using(database).update(
        nom_produit_snapshot="",
        fichier_nom_stockage_snapshot="",
        fichier_nom_telechargement_snapshot="",
    )


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_commande_language_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='lignecommande',
            name='fichier_nom_stockage_snapshot',
            field=models.CharField(blank=True, editable=False, max_length=500),
        ),
        migrations.AddField(
            model_name='lignecommande',
            name='fichier_nom_telechargement_snapshot',
            field=models.CharField(blank=True, editable=False, max_length=255),
        ),
        migrations.AddField(
            model_name='lignecommande',
            name='nom_produit_snapshot',
            field=models.CharField(blank=True, editable=False, max_length=255),
        ),
        migrations.RunPython(
            backfill_order_line_snapshots,
            clear_order_line_snapshots,
        ),
        migrations.AlterField(
            model_name='lignecommande',
            name='produit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.produit'),
        ),
    ]
