# Generated by Django 5.2.5 on 2026-09-13 13:13

import django.core.validators
import django.db.models.deletion
import django.db.models.expressions
from django.conf import settings
from django.db import migrations, models


def create_initial_stock_movements(apps, schema_editor):
    Produit = apps.get_model("shop", "Produit")
    StockMovement = apps.get_model("shop", "StockMovement")
    movements = []
    for product in Produit.objects.filter(stock__isnull=False).iterator():
        if product.fichier:
            continue
        movements.append(
            StockMovement(
                produit_id=product.pk,
                movement_type="INITIAL",
                quantity=product.stock,
                stock_before=0,
                stock_after=product.stock,
                product_id_snapshot=product.pk,
                product_name_snapshot=product.nom,
                reason="Reprise du stock existant lors de la création du journal",
                idempotency_key=f"inventory:initial:product:{product.pk}",
            )
        )
    StockMovement.objects.bulk_create(movements, ignore_conflicts=True)


def remove_initial_stock_movements(apps, schema_editor):
    StockMovement = apps.get_model("shop", "StockMovement")
    StockMovement.objects.filter(
        movement_type="INITIAL",
        idempotency_key__startswith="inventory:initial:product:",
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_inventory_integrity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('INITIAL', 'Stock initial'), ('MANUAL', 'Ajustement manuel'), ('RESERVATION', 'Réservation'), ('RELEASE', 'Libération'), ('SALE', 'Vente confirmée'), ('RESTOCK', 'Remise en stock')], max_length=20, verbose_name='Type de mouvement')),
                ('quantity', models.IntegerField(verbose_name='Variation')),
                ('stock_before', models.PositiveIntegerField(verbose_name='Stock avant')),
                ('stock_after', models.PositiveIntegerField(verbose_name='Stock après')),
                ('reason', models.TextField(verbose_name='Motif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('idempotency_key', models.CharField(editable=False, max_length=255, unique=True, verbose_name='Clé d’idempotence')),
                ('product_id_snapshot', models.PositiveBigIntegerField(editable=False, verbose_name='Identifiant produit')),
                ('product_name_snapshot', models.CharField(editable=False, max_length=255, verbose_name='Nom du produit')),
            ],
            options={
                'verbose_name': 'Mouvement de stock',
                'verbose_name_plural': 'Mouvements de stock',
                'ordering': ('-created_at', '-pk'),
            },
        ),
        migrations.AddField(
            model_name='commande',
            name='inventory_cycle',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='produit',
            name='low_stock_threshold',
            field=models.PositiveIntegerField(blank=True, help_text='Laissez vide pour désactiver l’alerte de stock faible.', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Seuil de stock faible'),
        ),
        migrations.AlterField(
            model_name='commande',
            name='inventory_status',
            field=models.CharField(choices=[('NONE', 'Sans réservation'), ('RESERVED', 'Stock réservé'), ('COMMITTED', 'Stock consommé'), ('RELEASED', 'Stock libéré'), ('RESTOCKED', 'Stock remis en inventaire')], default='NONE', editable=False, max_length=20),
        ),
        migrations.AddConstraint(
            model_name='produit',
            constraint=models.CheckConstraint(condition=models.Q(('low_stock_threshold__isnull', True), ('low_stock_threshold__gte', 0), _connector='OR'), name='product_low_stock_threshold_nonnegative'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to=settings.AUTH_USER_MODEL, verbose_name='Acteur staff'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='commande',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='shop.commande', verbose_name='Commande'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='ligne',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='shop.lignecommande', verbose_name='Ligne de commande'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='produit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='shop.produit', verbose_name='Produit'),
        ),
        migrations.RunPython(
            create_initial_stock_movements,
            remove_initial_stock_movements,
        ),
        migrations.AddConstraint(
            model_name='stockmovement',
            constraint=models.CheckConstraint(condition=models.Q(('stock_after', django.db.models.expressions.CombinedExpression(models.F('stock_before'), '+', models.F('quantity')))), name='stock_movement_balanced'),
        ),
        migrations.AddConstraint(
            model_name='stockmovement',
            constraint=models.CheckConstraint(condition=models.Q(('reason', ''), _negated=True), name='stock_movement_reason_not_empty'),
        ),
    ]
