# Generated by Django 5.2.5 on 2026-09-13 19:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0022_inventory_audit_trail'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderCancellation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('CUSTOMER', 'Client'), ('STAFF', 'Équipe')], max_length=20, verbose_name='Origine')),
                ('idempotency_key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Clé d’idempotence')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stripe_expiration_status', models.CharField(choices=[('NOT_REQUIRED', 'Non requise'), ('PENDING', 'À effectuer'), ('PROCESSING', 'En cours'), ('SUCCEEDED', 'Session expirée'), ('FAILED', 'Échec contrôlé')], default='NOT_REQUIRED', editable=False, max_length=20, verbose_name='Expiration Stripe')),
                ('stripe_expiration_attempted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('notification_sent_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('late_payment_detected_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('commande', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='cancellation', to='shop.commande', verbose_name='Commande')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_order_cancellations', to=settings.AUTH_USER_MODEL, verbose_name='Annulée par')),
            ],
            options={
                'verbose_name': 'Annulation de commande',
                'verbose_name_plural': 'Annulations de commande',
                'ordering': ('-created_at', '-pk'),
            },
        ),
    ]
