# Generated by Django 5.2.5 on 2026-09-21 20:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0024_order_fulfillment_integrity"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProduitImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="produits/galerie/")),
                (
                    "ordre",
                    models.PositiveIntegerField(
                        default=0,
                        verbose_name="Ordre d’affichage",
                    ),
                ),
                (
                    "texte_alternatif",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="Texte alternatif de l’image",
                    ),
                ),
                (
                    "texte_alternatif_fr",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        null=True,
                        verbose_name="Texte alternatif de l’image",
                    ),
                ),
                (
                    "texte_alternatif_de",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        null=True,
                        verbose_name="Texte alternatif de l’image",
                    ),
                ),
                (
                    "texte_alternatif_en",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        null=True,
                        verbose_name="Texte alternatif de l’image",
                    ),
                ),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                (
                    "produit",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images_secondaires",
                        to="shop.produit",
                    ),
                ),
            ],
            options={
                "ordering": ("ordre", "pk"),
                "indexes": [
                    models.Index(
                        fields=["produit", "ordre"],
                        name="shop_prodimg_order_idx",
                    )
                ],
            },
        ),
    ]
